# pin assignments
set_location_assignment PIN_H6 -to clk_12
set_location_assignment PIN_G5 -to clk_x
set_location_assignment PIN_A3 -to flash_clk
set_location_assignment PIN_A8 -to led[0]
set_location_assignment PIN_A9 -to led[1]
set_location_assignment PIN_A11 -to led[2]
set_location_assignment PIN_A10 -to led[3]
set_location_assignment PIN_B10 -to led[4]
set_location_assignment PIN_C9 -to led[5]
set_location_assignment PIN_C10 -to led[6]
set_location_assignment PIN_D8 -to led[7]
set_location_assignment PIN_E6 -to user_btn
set_instance_assignment -name IO_STANDARD "2.5 V SCHMITT TRIGGER" -to user_btn
set_location_assignment PIN_J5 -to sen_int1
set_location_assignment PIN_L4 -to sen_int2
set_location_assignment PIN_J7 -to sen_sdi
set_location_assignment PIN_K5 -to sen_sdo
set_location_assignment PIN_J6 -to sen_spc
set_location_assignment PIN_L5 -to sen_cs
set_location_assignment PIN_K6 -to sdram_a[0]
set_location_assignment PIN_M5 -to sdram_a[1]
set_location_assignment PIN_N5 -to sdram_a[2]
set_location_assignment PIN_J8 -to sdram_a[3]
set_location_assignment PIN_N10 -to sdram_a[4]
set_location_assignment PIN_M11 -to sdram_a[5]
set_location_assignment PIN_N9 -to sdram_a[6]
set_location_assignment PIN_L10 -to sdram_a[7]
set_location_assignment PIN_M13 -to sdram_a[8]
set_location_assignment PIN_N8 -to sdram_a[9]
set_location_assignment PIN_N4 -to sdram_a[10]
set_location_assignment PIN_M10 -to sdram_a[11]
set_location_assignment PIN_L11 -to sdram_a[12]
set_location_assignment PIN_M12 -to sdram_a[13]
set_location_assignment PIN_N6 -to sdram_ba[0]
set_location_assignment PIN_K8 -to sdram_ba[1]
set_location_assignment PIN_M9 -to sdram_clk
set_location_assignment PIN_M8 -to sdram_cke
set_location_assignment PIN_N7 -to sdram_cas
set_location_assignment PIN_M4 -to sdram_cs
set_location_assignment PIN_M7 -to sdram_ras
set_location_assignment PIN_K7 -to sdram_we
set_location_assignment PIN_E9 -to sdram_dqm[0]
set_location_assignment PIN_F12 -to sdram_dqm[1]
set_location_assignment PIN_D11 -to sdram_dq[0]
set_location_assignment PIN_G10 -to sdram_dq[1]
set_location_assignment PIN_F10 -to sdram_dq[2]
set_location_assignment PIN_F9 -to sdram_dq[3]
set_location_assignment PIN_E10 -to sdram_dq[4]
set_location_assignment PIN_D9 -to sdram_dq[5]
set_location_assignment PIN_G9 -to sdram_dq[6]
set_location_assignment PIN_F8 -to sdram_dq[7]
set_location_assignment PIN_F13 -to sdram_dq[8]
set_location_assignment PIN_E12 -to sdram_dq[9]
set_location_assignment PIN_E13 -to sdram_dq[10]
set_location_assignment PIN_D12 -to sdram_dq[11]
set_location_assignment PIN_C12 -to sdram_dq[12]
set_location_assignment PIN_B12 -to sdram_dq[13]
set_location_assignment PIN_B13 -to sdram_dq[14]
set_location_assignment PIN_A12 -to sdram_dq[15]
set_location_assignment PIN_B3 -to flash_cs
set_location_assignment PIN_A2 -to flash_di
set_location_assignment PIN_B2 -to flash_do
set_location_assignment PIN_H8 -to user_dio[0]
set_location_assignment PIN_K10 -to user_dio[1]
set_location_assignment PIN_H5 -to user_dio[2]
set_location_assignment PIN_H4 -to user_dio[3]
set_location_assignment PIN_J1 -to user_dio[4]
set_location_assignment PIN_J2 -to user_dio[5]
set_location_assignment PIN_L12 -to user_dio[6]
set_location_assignment PIN_J12 -to user_dio[7]
set_location_assignment PIN_J13 -to user_dio[8]
set_location_assignment PIN_K11 -to user_dio[9]
set_location_assignment PIN_K12 -to user_dio[10]
set_location_assignment PIN_J10 -to user_dio[11]
set_location_assignment PIN_H10 -to user_dio[12]
set_location_assignment PIN_H13 -to user_dio[13]
set_location_assignment PIN_G12 -to user_dio[14]
set_location_assignment PIN_M3 -to pio[0]
set_location_assignment PIN_L3 -to pio[1]
set_location_assignment PIN_M2 -to pio[2]
set_location_assignment PIN_M1 -to pio[3]
set_location_assignment PIN_N3 -to pio[4]
set_location_assignment PIN_N2 -to pio[5]
set_location_assignment PIN_K2 -to pio[6]
set_location_assignment PIN_K1 -to pio[7]
set_location_assignment PIN_B4 -to ftdi_rx
set_location_assignment PIN_A4 -to ftdi_tx
